[window]
decorations = "None"
padding = { x = 5, y = 5 }

[font]
size = 28
# offset = { x = 2, y = -1 }
# glyph_offset = { x = 0, y = 0 }

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[font.normal]
family = "Iosevka Custom"
style = "SemiLight"

# family = "Comic Code"
# style = "Regular"

# family = "FiraCode Nerd Font Mono"
# style = "Regular"

# family = "Cascadia Code"
# style = "SemiLight"

[font.bold]
family = "Iosevka Custom"
style = "Medium"

# family = "Comic Code"
# style = "Medium"

# family = "FiraCode Nerd Font Mono"
# style = "Medium"

# family = "Cascadia Code"
# style = "Regular"

[font.italic]
family = "Iosevka Custom"
style = "SemiLight Italic"

# family = "Comic Code"
# style = "Regular Italic"

# family = "FiraCode Nerd Font Mono"
# style = "Regular Italic"

# family = "Cascadia Code"
# style = "SemiLight Italic"

[font.bold_italic]
family = "Iosevka Custom"
style = "Medium Italic"

# family = "Comic Code"
# style = "Medium Italic"

# family = "FiraCode Nerd Font Mono"
# style = "Medium Italic"

# family = "Cascadia Code"
# style = "Regular Italic"

[cursor]
style = { shape = "Block", blinking = "Off" }

[colors.primary]
background = "#181818"
foreground = "#e4e4e4"

[colors.cursor]
text = "#000000"
cursor = "#ffdd33"

[colors.selection]
text = "#f4f4ff"
background = "#453d41"

[colors.normal]
black   = "#181818"
red     = "#ff0a36"
green   = "#42dc00"
yellow  = "#ffdb00"
blue    = "#90aa9e"
magenta = "#a095cb"
cyan    = "#92a7cb"
white   = "#e4e4e4"

[colors.bright]
black   = "#54494e"
red     = "#ff3851"
green   = "#42dc00"
yellow  = "#ffdb00"
blue    = "#90aa9e"
magenta = "#afafda"
cyan    = "#92a7cb"
white   = "#f5f5f5"
